### ISSUE TITLE
Does not accept a custom host

### ISSUE THREAD

**Issue by rbtr** [IonicaBizau/github-stats#15]
Although gh.js supports custom `host` (for example, enterprise github url), that cannot be passed as a cli option due to [this](https://github.com/IonicaBizau/node-gh-polyglot/issues/13) limitation in `node-gh-polyglot`.

I would like to be able to `github-stats` against my company github account, but currently can't due to this limitation. It looks like an easy fix, so I will go ahead and open a PR if that sounds good!

**Comment by IonicaBizau** [comment]
Sure! That would be great!

I'm not familiar with GitHub Enterprise, but I understand the concept and probably just by being able to set the host, you will be able to set that.

Thanks!
