### ISSUE TITLE
Legend of pie-chart is broken

### ISSUE THREAD

**Issue by adius** [IonicaBizau/github-stats#7]
![screen shot 2016-06-06 at 16 00 01](https://cloud.githubusercontent.com/assets/969983/15828696/d65774fe-2bff-11e6-8053-5ceb5fa7225f.png)

I'm using iTerm 2

**Comment by IonicaBizau** [comment]
@adius It's probably because I used some kind of emoji character there. 😂 On Linux the ANSI color is applied, but on OSX it is displayed natively.

It should be fixed here: https://github.com/IonicaBizau/node-cli-pie

**Comment by IonicaBizau** [comment]
Fixed by @coltaemanuela in https://github.com/IonicaBizau/node-cli-pie/pull/18
